name: PR Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Fluent.Garmin.sln
      
    - name: Build
      run: dotnet build src/Fluent.Garmin.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/Fluent.Garmin.sln --configuration Release --no-build --verbosity normal