name: Official Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'Official release of Fluent.Garmin library.'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate version format
      run: |
        if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Version must be in format X.Y.Z (e.g., 1.0.0)"
          exit 1
        fi
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/Fluent.Garmin.sln
      
    - name: Build
      run: dotnet build src/Fluent.Garmin.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/Fluent.Garmin.sln --configuration Release --no-build --verbosity normal
      
    - name: Pack NuGet package
      run: dotnet pack src/Fluent.Garmin/Fluent.Garmin.csproj --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ github.event.inputs.version }}
      
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push ./artifacts/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        
    - name: Publish to NuGet.org (if API key is configured)
      run: |
        if [ -n "${{ secrets.NUGET_API_KEY }}" ]; then
          echo "Publishing to NuGet.org..."
          dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        else
          echo "NUGET_API_KEY not configured, skipping NuGet.org publish"
        fi
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        body: |
          ${{ github.event.inputs.release_notes }}
          
          ### Installation
          
          **From NuGet.org:**
          ```bash
          dotnet add package Fluent.Garmin --version ${{ github.event.inputs.version }}
          ```
          
          **From GitHub Packages:**
          ```bash
          dotnet add package Fluent.Garmin --version ${{ github.event.inputs.version }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          ```
        draft: false
        prerelease: false
        files: ./artifacts/*.nupkg
        
    - name: Update any existing pre-release
      run: |
        # This step will mark any existing pre-release as not pre-release anymore
        # since we now have an official release
        echo "Official release v${{ github.event.inputs.version }} published successfully"